---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-9
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9-aarch64
        - latest-aarch64
      dockerfile: 9/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.3
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.3-aarch64
      dockerfile: 9.3/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.4
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.4-aarch64
      dockerfile: 9.4/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.5-aarch64
      dockerfile: 9.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.6-aarch64
      dockerfile: 9.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-9
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9-amd64
        - latest-amd64
      dockerfile: 9/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.3
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.3-amd64
      dockerfile: 9.3/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.4
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.4-amd64
      dockerfile: 9.4/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.5-amd64
      dockerfile: 9.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.6-amd64
      dockerfile: 9.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-9
    image: plugins/manifest
    settings:
      spec: 9/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9.3
    image: plugins/manifest
    settings:
      spec: 9.3/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9.4
    image: plugins/manifest
    settings:
      spec: 9.4/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9.5
    image: plugins/manifest
    settings:
      spec: 9.5/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9.6
    image: plugins/manifest
    settings:
      spec: 9.6/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: healthcheck
    image: ubuntu
    environment:
      HEALTHCHECKS_URL:
        from_secret: healthchecks_url
    commands:
      - apt-get update
      - apt-get -y install curl
      - |
        if [ ${DRONE_BUILD_STATUS} = success ]; then
          curl --retry 3 $${HEALTHCHECKS_URL}
        else
          curl --retry 3 $${HEALTHCHECKS_URL}/fail
        fi
    when:
      status: [success, failure]

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: 8f51b8a3d6ab90ba6c99858d32160bbc35c11e0c09b9a9967b3614cbf7791ce3

...
