---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-8.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.5-aarch64
      dockerfile: 8.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.6-aarch64
      dockerfile: 8.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8.7
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.7-aarch64
      dockerfile: 8.7/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8-aarch64
        - latest-aarch64
      dockerfile: 8/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9-aarch64
      dockerfile: 9/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.1
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.1-aarch64
      dockerfile: 9.1/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-8.5
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.5-amd64
      dockerfile: 8.5/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8.6
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.6-amd64
      dockerfile: 8.6/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8.7
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8.7-amd64
      dockerfile: 8.7/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-8
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 8-amd64
        - latest-amd64
      dockerfile: 8/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9-amd64
      dockerfile: 9/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-9.1
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-rocky
      tags:
        - 9.1-amd64
      dockerfile: 9.1/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-8.5
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 8.5/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-8.6
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 8.6/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-8.7
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 8.7/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-8
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 8/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 9/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-9.1
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-rocky
      spec: 9.1/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: healthcheck
    image: ubuntu
    environment:
      HEALTHCHECKS_URL:
        from_secret: healthchecks_url
    commands:
      - apt-get update
      - apt-get -y install curl
      - |
        if [ ${DRONE_BUILD_STATUS} = success ]; then
          curl --retry 3 $${HEALTHCHECKS_URL}
        else
          curl --retry 3 $${HEALTHCHECKS_URL}/fail
        fi
    when:
      status: [success, failure]

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: ce0b2a86bc440040ae22d7a2ee7055886d2d4ffb39c17d08329189e082b3b6fa

...
